# Generated by Django 2.1 on 2019-08-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('Santander', 'Santander'), ('BB', 'Banco do Brasil'), ('ITAU', 'ITAU')], max_length=200)),
                ('money_in_account', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_gasto', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='gastos',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Usuarios'),
        ),
        migrations.AddField(
            model_name='conta',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Usuarios'),
        ),
    ]
