# Generated by Django 2.1 on 2019-08-15 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('banco', models.CharField(choices=[('Santander', 'Santander'), ('BB', 'Banco do Brasil'), ('ITAU', 'ITAU')], max_length=200)),
                ('money_in_account', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_conta', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('descricao_gasto', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('id_gastos', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='gastos',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Usuarios'),
        ),
        migrations.AddField(
            model_name='conta',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Usuarios'),
        ),
    ]
