# Generated by Django 2.1 on 2019-08-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190815_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null='True'),
            preserve_default='True',
        ),
    ]
