# Generated by Django 2.1 on 2019-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20190817_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='number',
            field=models.IntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='number',
            field=models.IntegerField(verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='number',
            field=models.IntegerField(verbose_name='Number'),
        ),
    ]
